# Generated by Django 4.1.4 on 2023-02-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateTimeField()),
                ('nome_tutor', models.CharField(max_length=100)),
                ('nome_animal', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prontuário',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotacoes', models.CharField(max_length=10000)),
                ('data_retorno', models.DateTimeField()),
            ],
        ),
    ]
