# Generated by Django 4.1.4 on 2023-02-23 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prontuário',
            new_name='Prontuario',
        ),
        migrations.AlterModelOptions(
            name='dados',
            options={'verbose_name': 'Livro'},
        ),
        migrations.AlterModelOptions(
            name='prontuario',
            options={'verbose_name': 'Prontuario'},
        ),
    ]
