# Generated by Django 4.1.4 on 2023-02-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_rename_prontuário_prontuario_alter_dados_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dados',
            options={'verbose_name': 'Dado'},
        ),
        migrations.AlterField(
            model_name='dados',
            name='data_atendimento',
            field=models.DateField(auto_now=True),
        ),
    ]
