# Generated by Django 4.1.4 on 2023-02-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_dados_options_alter_dados_data_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='data_retorno',
            field=models.DateField(),
        ),
    ]
