# Generated by Django 4.1.4 on 2023-02-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_prontuario_data_retorno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='data_atendimento',
            field=models.DateField(),
        ),
    ]
